services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data/db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis
    container_name: sessions
